### ISSUE TITLE
Detectability

### ISSUE THREAD

**Issue by neopostmodern** [loritaylorbear/Groove-Shredder#1]
For "educational purposes only" I would like to know if someone could violate local copyright restrictions without even getting noticed. As far as I have seen the Add-on basicly multiplies the song-requests and then missuses them - right?
Do you have any idea if "real" requests can be distinguished from the "false" ones? And if so, do you know of any attempts by grooveshark to stop this violation of their terms of use?

**Comment by rgarg8** [comment]
When I say that it is for educational purposes only, I mean it. My intention
is not to support copyright violation or malicious use, if you partake in
such activities you're on your own.

**Comment by neopostmodern** [comment]
That was not my point.
Just look, there are probably 10k+ people using this add-on.
And if there was just one among them MISSusing it, I wondered if they could track him down.
I am not planing to use it myself, as I don't care about just listening to it online,
but I am generally interested in any kind of copyright-trouble caused by the uncontrollable Internet.

**Comment by rgarg8** [comment]
"but I am generally interested in any kind of copyright-trouble caused by the uncontrollable Internet."

That would be your own responsibility. I make no assumptions as to the secrecy or stealth of my software and I suggest you do the same, as far as I can tell it should be possible to detect.
