### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by ghost** [loritaylorbear/Groove-Shredder#2]
Hey,  

I see a folder called chrome. 
Would be nice if this puppy worked with chrome, if its possible.

This plugin is really nice to use BTW.

thanks for the hard work !!

G

**Comment by rgarg8** [comment]
It is currently impossible to make this add-on for chrome. They simply do not give developers the amount of control that is needed here.

Here's some references:
http://stackoverflow.com/questions/5020217/is-there-such-a-thing-as-the-tamper-data-firefox-plugin-for-chrome
http://stackoverflow.com/questions/4869711/is-there-an-extension-like-tamperdata-for-chrome

**Comment by ghost** [comment]
ok makes sense !

stick with FF then for me :)

thanks again for the reply and the plugin

Ged

On 28 June 2011 19:39, rgarg8
reply@reply.github.com
wrote:
