### ISSUE TITLE
Auto ignore auto download if mp3 already exists in folder?

### ISSUE THREAD

**Issue by tbs** [loritaylorbear/Groove-Shredder#3]
The alert "File exists in target location. Overwrite?" is pure annoyance. Is there any way to auto ignore it in auto download mode?

Thank you!

**Comment by rgarg8** [comment]
I have resolved this in Groove Shredder version 1.12. I am uploading the source now and submitting it to the Mozilla AMO, it will be available under the "Versions" link. I will post that here in a bit.

**Comment by rgarg8** [comment]
Versions page: https://addons.mozilla.org/en-US/firefox/addon/grooveshredder/versions/

Direct link: https://addons.mozilla.org/en-US/firefox/addon/305091/eula/127078?src=version-history
